#!/usr/bin/env bats
# tests/manifest.bats — plugin/marketplace/hooks manifest schema checks.
#
# These are read-only tests of files already in the repo. No sandboxing
# needed because nothing writes to disk — we only parse JSON.

load "$BATS_TEST_DIRNAME/setup.bash"

@test "plugin.json is valid JSON" {
  run python3 -m json.tool "$REPO_ROOT/.claude-plugin/plugin.json"
  [ "$status" -eq 0 ]
}

@test "plugin.json has required fields" {
  run python3 -c "
import json
d = json.load(open('$REPO_ROOT/.claude-plugin/plugin.json'))
for k in ('name', 'version', 'description', 'skills'):
    assert k in d, f'missing: {k}'
"
  [ "$status" -eq 0 ]
}

@test "plugin.json does not carry the unsupported 'hooks' field" {
  run python3 -c "
import json
d = json.load(open('$REPO_ROOT/.claude-plugin/plugin.json'))
assert 'hooks' not in d, 'hooks field must be absent — auto-discovered from hooks/hooks.json'
"
  [ "$status" -eq 0 ]
}

@test "plugin.json version is SemVer" {
  run python3 -c "
import json, re
v = json.load(open('$REPO_ROOT/.claude-plugin/plugin.json'))['version']
assert re.fullmatch(r'\d+\.\d+\.\d+', v), f'not SemVer: {v}'
"
  [ "$status" -eq 0 ]
}

@test "marketplace.json is valid JSON" {
  run python3 -m json.tool "$REPO_ROOT/.claude-plugin/marketplace.json"
  [ "$status" -eq 0 ]
}

@test "marketplace.json plugins[].source starts with './'" {
  run python3 -c "
import json
d = json.load(open('$REPO_ROOT/.claude-plugin/marketplace.json'))
for i, p in enumerate(d['plugins']):
    s = p.get('source')
    assert isinstance(s, str) and s.startswith('./'), f'plugins[{i}].source invalid: {s!r}'
"
  [ "$status" -eq 0 ]
}

@test "marketplace.json has no version field on plugins[]" {
  # Regression: per Claude Code schema, plugin entries here should not
  # carry a version (it lives in plugin.json only).
  run python3 -c "
import json
d = json.load(open('$REPO_ROOT/.claude-plugin/marketplace.json'))
for i, p in enumerate(d['plugins']):
    assert 'version' not in p, f'plugins[{i}] must not contain version'
"
  [ "$status" -eq 0 ]
}

@test "hooks/hooks.json is valid JSON with required events" {
  run python3 -c "
import json
d = json.load(open('$REPO_ROOT/hooks/hooks.json'))
assert 'hooks' in d, 'root key hooks missing'
for evt in ('PostToolUse', 'PostToolUseFailure', 'Stop'):
    assert evt in d['hooks'], f'event {evt} missing'
"
  [ "$status" -eq 0 ]
}

@test "hooks/hooks.json commands reference \${CLAUDE_PLUGIN_ROOT}" {
  # Hooks must be portable across install paths — anchoring scripts to
  # CLAUDE_PLUGIN_ROOT (set by Claude Code) is the only correct way.
  run python3 -c "
import json
d = json.load(open('$REPO_ROOT/hooks/hooks.json'))
bad = []
for evt, groups in d['hooks'].items():
    for g in groups:
        for h in g.get('hooks', []):
            cmd = h.get('command', '')
            if '\${CLAUDE_PLUGIN_ROOT}' not in cmd:
                bad.append(f'{evt}: {cmd}')
assert not bad, bad
"
  [ "$status" -eq 0 ]
}

@test "every skill directory has a SKILL.md with valid frontmatter" {
  run python3 -c "
import os, re
root = '$REPO_ROOT/skills'
bad = []
for name in sorted(os.listdir(root)):
    if name.startswith('.'):
        continue
    path = os.path.join(root, name, 'SKILL.md')
    if not os.path.isfile(path):
        bad.append(f'{name}: missing SKILL.md'); continue
    head = open(path).read(2000)
    if not head.startswith('---\n'):
        bad.append(f'{name}: no frontmatter'); continue
    fm = head.split('---\n', 2)[1]
    for k in ('name:', 'description:'):
        if k not in fm:
            bad.append(f'{name}: missing {k}')
    # Regression guard: name must not contain ':' — plugin prefix is
    # auto-generated by Claude Code. galmuri hit an install failure with
    # 'name: galmuri:distill'.
    n = re.search(r'^name:\s*(\S+)', fm, re.M)
    if n and ':' in n.group(1):
        bad.append(f'{name}: name contains colon ({n.group(1)})')
assert not bad, bad
"
  [ "$status" -eq 0 ]
}

@test "skill directory name matches SKILL.md frontmatter name" {
  run python3 -c "
import os, re
root = '$REPO_ROOT/skills'
bad = []
for name in sorted(os.listdir(root)):
    if name.startswith('.'):
        continue
    path = os.path.join(root, name, 'SKILL.md')
    if not os.path.isfile(path):
        continue
    head = open(path).read(2000)
    fm = head.split('---\n', 2)[1] if head.startswith('---\n') else ''
    m = re.search(r'^name:\s*(\S+)', fm, re.M)
    if not m or m.group(1) != name:
        bad.append(f'{name}: dir name vs frontmatter name mismatch ({m.group(1) if m else None})')
assert not bad, bad
"
  [ "$status" -eq 0 ]
}

@test "plugin version, VERSION file, and CHANGELOG top entry agree" {
  run python3 -c "
import json, re, os
root = '$REPO_ROOT'
plugin_v = json.load(open(f'{root}/.claude-plugin/plugin.json'))['version']
version_file = open(f'{root}/VERSION').read().strip()
changelog = open(f'{root}/CHANGELOG.md').read()
m = re.search(r'^## \[(\d+\.\d+\.\d+)\]', changelog, re.M)
top_changelog = m.group(1) if m else None
assert plugin_v == version_file == top_changelog, (
    f'mismatch: plugin.json={plugin_v} VERSION={version_file} CHANGELOG top={top_changelog}'
)
"
  [ "$status" -eq 0 ]
}

@test "README.md and README.ko.md exist and reference the same install URL" {
  [ -f "$REPO_ROOT/README.md" ]
  [ -f "$REPO_ROOT/README.ko.md" ]
  grep -q "/plugin marketplace add https://github.com/jazz1x/harnish.git" "$REPO_ROOT/README.md"
  grep -q "/plugin marketplace add https://github.com/jazz1x/harnish.git" "$REPO_ROOT/README.ko.md"
}
